### ISSUE TITLE
Move enabled_theme to lca_info from zkpylons

### ISSUE THREAD

**Issue by KathyReid** [zookeepr/zookeepr#365]
### User story

As an Administrator of ZooKeepr, I want to have the enabled_theme configuration value as part of the overall configuration of ZooKeepr, making it easy both to get an instance up and running, and also to switch Themes if necessary. 

### Acceptance criteria

* @TODO - sorry I don't know what's required technically here

@jhesketh I think this one may also be fixed, because I say this in an lca_info file :-)

**Comment by jhesketh** [comment]
I have moved the enabled_theme into the lca_info file. However, we might need to move it back out if we dbify lca_info. I'll mark this as closed for now, but we may need to open it again if we undo the work. At which point we can look at our options of where to put it. If we can't store it in the database I'm thinking the next best place would be in the production.ini file so that only 1 file needs editing on deployment.
